# Generated by Django 4.2.5 on 2023-11-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistapp', '0002_post_art_name_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=1000),
            preserve_default=False,
        ),
    ]
