# Generated by Django 4.2.5 on 2023-11-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistapp', '0006_cartitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_table',
        ),
    ]
