# Generated by Django 4.2.5 on 2023-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistapp', '0007_alter_cartitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(default='static/user_profiles/userpic.png', upload_to='carts/'),
        ),
    ]
