# Generated by Django 4.2.5 on 2023-10-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('FullName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('MobileNumber', models.CharField(max_length=20, unique=True)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('TypeOfArtist', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'artist_table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('FullName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('MobileNumber', models.CharField(max_length=20, unique=True)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
