# Generated by Django 4.2.5 on 2023-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=10),
        ),
        migrations.AlterField(
            model_name='artist',
            name='TypeOfArtist',
            field=models.CharField(choices=[('Aesthetic drawings', 'AD'), ('Traditional Arts', 'TA'), ('Sculptures Arts', 'SA'), ('Anime/Manga Arts', 'MA'), ('Real life Drawings', 'RD'), ('Doodle Art', 'DA'), ('Pen Drawings', 'PD'), ('Nature Arts', 'NA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=10),
        ),
    ]
