# Generated by Django 4.2.5 on 2023-10-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_admin_id_alter_admin_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='TypeOfArtist',
            field=models.CharField(choices=[('Aesthetic drawings', 'Aesthetic drawings'), ('Traditional Arts', 'Traditional Arts'), ('Sculptures Arts', 'Sculptures Arts'), ('Anime/Manga Arts', 'Anime/Manga Arts'), ('Real life Drawings', 'Real life Drawings'), ('Doodle Art', 'Doodle Art'), ('Pen Drawings', 'Pen Drawings'), ('Nature Arts', 'Nature Arts')], max_length=100),
        ),
    ]
