# Generated by Django 4.2.5 on 2023-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_artist_typeofartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='userpic.png', upload_to='user_profiles/'),
        ),
    ]
