# Generated by Django 4.2.5 on 2023-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Add Bio✏️'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(default='userpic.png', upload_to='user_pics/'),
        ),
    ]
