# Generated by Django 4.2.5 on 2023-10-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_user_profile_pic_user_bio_user_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(default='userpic.jpg', upload_to='user_pics/'),
        ),
    ]
