# Generated by Django 4.2.5 on 2023-10-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_user_bio_remove_user_user_pic_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='user2086', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
