# Generated by Django 4.2.5 on 2023-10-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_profile_id_profile_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile_table',
        ),
    ]
