# Generated by Django 4.2.5 on 2023-10-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
