# Generated by Django 4.2.5 on 2023-11-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_delete_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='MobileNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
