# Generated by Django 4.2.5 on 2023-11-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_post1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post1',
            table='post1_table',
        ),
    ]
