# Generated by Django 4.2.5 on 2023-11-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_alter_post1_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
